version: "3.8"
services:
  app:
    build: .
    ports:
      - "3010:3000"
    volumes:
      - .:/app # твой код
      - /app/node_modules # node_modules останется внутри контейнера
    command: npm start
    environment:
      NODE_ENV: development
